$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pred-maint-env
description: TensorFlow environment for predictive maintenance models
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: conda.yaml
